-- SQLite
SELECT * FROM darbuotojai;
-- SELECT GIMIMO_DATA FROM darbuotojai;
-- SELECT VARDAS, PAVARDĖ, PAREIGOS FROM darbuotojai;
-- SELECT DISTINCT SKYRIUS_PAVADINIMAS FROM darbuotojai;
-- SELECT * FROM DARBUOTOJAI WHERE SKYRIUS_PAVADINIMAS = "Gamybos"
-- SELECT PAREIGOS FROM DARBUOTOJAI WHERE VARDAS = "Giedrius"
-- SELECT * FROM DARBUOTOJAI WHERE GIMIMO_DATA = "1986-09-19"
-- SELECT * FROM DARBUOTOJAI WHERE PAVARDĖ = "Sabutis"
-- SELECT VARDAS, PAVARDĖ FROM DARBUOTOJAI WHERE SKYRIUS_PAVADINIMAS = "Gamybos"
